#!/usr/bin/perl
# Copyright (c) 2012 Benjamin Nadland <benjamin.nadland@freenet.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use 5.010;
use strict;
use warnings;

use Data::Dumper;
use Mojo::UserAgent;

my $ua;
my $message;
my $result;
my @links;

$ua = Mojo::UserAgent->new;

if ($#ARGV < 0) {
  die "You need to provide at least one channel name!\n";
}

# XXX: additional pages:
# http://www.youtube.com/user/TotalHalibut/videos?sort=dd&view=u&page=2

for my $arg (0 .. $#ARGV) {
  my $channelname = $ARGV[$arg];

	$result = $ua->get('https://www.youtube.com/user/' . $channelname .'/videos')
		->res->dom('a');
}

foreach my $tag (@$result) {
	if ($tag->{href}) {
		if ($tag->{href} =~ m{/watch\?v=(.*)\&feat.*} ) {
			push @links, $1;
		}
	}
}

foreach my $link (@links) {
	say $link;
}
